### ISSUE TITLE
About WonderWitch & Games 

### ISSUE THREAD

**Issue by AngelofMe** [williehwc/wonderdroid-x#10]
I got some screenshots
![SQ5LNH1IEoKM6XoT+B0+BTqKjHwJpAAAAAElFTkSuQmCC](https://user-images.githubusercontent.com/26894447/173194766-cc89352e-7d69-4841-8caa-8cf5aedf3ca3.png)
![images(1)](https://user-images.githubusercontent.com/26894447/173194769-7e4d1c73-d295-4be0-8f50-4afb7460e91c.jpg)
![images](https://user-images.githubusercontent.com/26894447/173194771-2f22e2cf-0973-4769-9cfd-16e1df7b2ee6.png)
![images(1)](https://user-images.githubusercontent.com/26894447/173194774-60e7f78b-b8e6-4e51-9047-81233dec7adc.png)
![images(2)](https://user-images.githubusercontent.com/26894447/173194776-8752a22d-4e73-4884-ba2b-29f76cd308ab.jpg)
![images(2)](https://user-images.githubusercontent.com/26894447/173194777-12d84d55-4a53-4f6e-883a-4ebce7f6df63.png)
![images(3)](https://user-images.githubusercontent.com/26894447/173194778-8ede209d-e2aa-4a91-9d1d-282d0ff4cce5.jpg)
![images(3)](https://user-images.githubusercontent.com/26894447/173194779-d8d27a5d-c9dd-42fd-9c81-457eb1cb4a4e.png)
![images(4)](https://user-images.githubusercontent.com/26894447/173194780-bf95baa5-396a-44f2-92c2-a48979e5b419.jpg)
![images(4)](https://user-images.githubusercontent.com/26894447/173194781-ebf882c5-e386-423f-8616-7c470b4f693b.png)
![images(5)](https://user-images.githubusercontent.com/26894447/173194783-18ea5e2c-4c87-4200-95da-4fa43c8dacc8.png)

MiracleMage & Oswan
Oswan based on Cygne
Mednafen based on Cygne
Will Wonderdroid X support WonderWitch & Games?

WWGP games download
2001
http://wwgp.qute.co.jp/2001/allworks.htm
http://wwgp.qute.co.jp/2001/entry2001a.zip
http://wwgp.qute.co.jp/2001/entry2001b.zip
http://wwgp.qute.co.jp/2001/entry2001c.zip
2002
http://wwgp.qute.co.jp/2002/allworks.htm
http://wwgp.qute.co.jp/2002/entry/wwgp2002_game_entry.zip
http://wwgp.qute.co.jp/2002/entry/wwgp2002_tool_entry.zip
http://wwgp.qute.co.jp/2002/entry/wwgp2002_hard_entry.zip
2003
http://wwgp.qute.co.jp/2003/entries/index.html
http://wwgp.qute.co.jp/2003/entries/wwgp2003entry.zip

LHA or LZH is a freeware compression utility and associated file format.
you can use 7zip or zarchiver to extract lha/lzh files

**Comment by AngelofMe** [comment]
- SRAM/EEPROM Size
       00 - 0k
       01 - 64k SRAM
       02 - 256k SRAM
       03 - 1M SRAM (Taikyoku Igo Heisei Kiin)
       04 - 2M SRAM (WonderWitch)
       10 - 1k EEPROM
       20 - 16k EEPROM
       50 - 8k EEPROM

**Comment by AngelofMe** [comment]
- SRAM/EEPROM Size
       00 - 0k
       01 - 64k SRAM
       02 - 256k SRAM
       03 - 1M SRAM (Taikyoku Igo Heisei Kiin)
       04 - 2M SRAM (WonderWitch)
       10 - 1k EEPROM
       20 - 16k EEPROM
       50 - 8k EEPROM

**Comment by williehwc** [comment]
Yes, I know about the SRAM/EEPROM sizes.
I'll test WonderWitch and get back to you.
