### ISSUE TITLE
useless option & portrait redesign

### ISSUE THREAD

**Issue by AngelofMe** [williehwc/wonderdroid-x#12]
please remove "Show game select background"
I think this emulator doesn't need show me 2 same duplicate PNG/JPG files
landscape no problem
but portrait not good
![Screenshot_20220613-232741_Trebuchet](https://user-images.githubusercontent.com/26894447/173394746-c729cc2a-f85c-42cd-a36f-b9bb78a1d3db.png)
![Screenshot_20220613-232701_Trebuchet](https://user-images.githubusercontent.com/26894447/173394802-1d330096-76c4-4289-ad57-caf36b0653bc.png)
![image2](https://user-images.githubusercontent.com/26894447/173394811-68bad6bc-ed4f-44be-aab9-9988fac13114.png)
![image3](https://user-images.githubusercontent.com/26894447/173395847-8b52539f-6e0d-4736-95e2-21bfa0ca66dd.png)

**Comment by AngelofMe** [comment]
another feature
Text Warp
Warp Words
what's the name of my file? Am I Playing Alchemist M...elier (Japan)?  Alchemist M...elier (Japan) is not a game name/title
![Screenshot_20220614-000453_Trebuchet](https://user-images.githubusercontent.com/26894447/173397022-7f20ec1a-5382-484a-8250-eadacf2132ab.png)
![Screenshot_20220614-000513_Trebuchet](https://user-images.githubusercontent.com/26894447/173397045-bf44a802-f444-4c2e-986d-5202b244bc31.png)
![Screenshot_20220614-000614_Trebuchet](https://user-images.githubusercontent.com/26894447/173397049-098d8e90-2eec-4fa7-8b86-ae35e22a16d0.png)
![Screenshot_20220614-000627_Trebuchet](https://user-images.githubusercontent.com/26894447/173397055-a966cf85-7064-4a53-9dfa-887a9bf6863b.png)
![Screenshot_20220614-000711_Trebuchet](https://user-images.githubusercontent.com/26894447/173397061-ac781f52-114f-43fb-b4e4-73680723e463.png)

**Comment by AngelofMe** [comment]
Longest WSC game title
Kidou Senshi Gundam - Giren no Yabou - Tokubetsu Hen - Aoki Hoshi no Hasha (Japan)

**Comment by williehwc** [comment]
- I am not removing an option unless there is universal feedback it is unnecessary. If you do not like the option, you can turn it off.
- I will consider making the filename display longer.
