### ISSUE TITLE
Save data erased

### ISSUE THREAD

**Issue by Blueboy1821** [williehwc/wonderdroid-x#17]
Minimized a game. Went back in and it restarted. Wouldn't let me load game, even though the save files are in the folder. I'm really bummed, man.

**Comment by williehwc** [comment]
Sounds awful, sorry about that. As you may have seen in other issues, I am currently transitioning the engine/core to Mednafen, which should help a lot with performance and stability. Development will wrap up next month, testing will be performed throughout September, and I plan to release the update in October.

If you encounter this problem again, please try to load the automatic state (usually once is enough, but you may need to load multiple times). When you switch from the app, a state is automatically saved, so it should get you back to where you were.

I also understand if you will be switching to another emulator. Thanks for trying out this one.

**Comment by Blueboy1821** [comment]
I figured out that if I just reload a manual save state a few times, my
data comes back. I've been saving normally and saving state together for
redundancy.

Charles Sanders
Research Associate II
XBiotech

**Comment by Blueboy1821** [comment]
Thank you for your response. I plan on staying with this emulator.

Charles Sanders
Research Associate II
XBiotech
