### ISSUE TITLE
Publishing in F-Droid

### ISSUE THREAD

**Issue by Bubu** [williehwc/wonderdroid-x#2]
Hi, the original wonderdroid app was published in [F-Droid](https://f-droid.org/) but has since been archived, so it's not available anymore.

Would you support this version being packaged for F-Droid as a replacement? See the request for packaging issue here: https://gitlab.com/fdroid/rfp/issues/910

**Comment by williehwc** [comment]
Hi @Bubu, sorry about the delayed response; I don't check Issues very often.
If you are still interested in packaging this fork for F-Droid, I give my support.

**Comment by Bubu** [comment]
I added it to f-droid. It should be available from there within 1-2 days.
