### ISSUE TITLE
Undo Load/Save State

### ISSUE THREAD

**Issue by AngelofMe** [williehwc/wonderdroid-x#26]
Undo Load State
If a state was loaded, content will go back to the state prior to loading.

Undo Save State
If a state was overwritten, it will roll back to the previous save state.

Rewind
Return to a previous point in recent gameplay. This causes severe performance hit when playing.

**Comment by williehwc** [comment]
Undo load/save state is already implemented.
As for rewind, as you wrote, "This causes severe performance hit when playing", so I haven't implemented it.
