### ISSUE TITLE
no need to move copy games to Android/data

### ISSUE THREAD

**Issue by soundsnow** [williehwc/wonderdroid-x#39]
https://github.com/mupen64plus-ae/mupen64plus-ae

you can download it to test
https://github.com/mupen64plus-ae/mupen64plus-ae/actions/workflows/continuous-integration-workflow.yml?query=branch%3Amaster

like Mupen64 Plus FZ Android Edition
you doesn't need to move copy files to Android/data
let app know where folders your all selected files are
and it doesn't rescan all files after you exit then open the app
I don't know how it does it
I've only imported 15GB games once, and after that I didn't have to wait unless I manually rescanned the files after deleting/adding the games

**Comment by williehwc** [comment]
Sorry, but adding support for direct reading of other folders will require modifications to a lot of existing code, possibly including the Mednafen core, which I would like to avoid to not overcomplicate future updates. Also, having a built-in file management system was requested in the past and seems to be preferred.
