### ISSUE TITLE
custom palette for all emulators

### ISSUE THREAD

**Issue by soundsnow** [williehwc/wonderdroid-x#57]
![B8SHu](https://user-images.githubusercontent.com/109885044/195504904-1178eaff-0c7c-4b6f-8754-560a06bd49dd.png)
![45c7a77f498b6ac0aec8a52ddf41fa3d50858cb1_2_690x385](https://user-images.githubusercontent.com/109885044/195506278-09996908-2e39-42c6-a708-d10df4008bf7.jpg)
![gimp-palette](https://user-images.githubusercontent.com/109885044/195506293-4f35a0a2-f559-411f-8904-422f84a9b2d0.png)
![maxresdefault](https://user-images.githubusercontent.com/109885044/195506297-f1b73333-0358-415d-a3f8-ee0116dc368c.jpg)
![photo_4](https://user-images.githubusercontent.com/109885044/195506300-b5f4efa5-fbeb-400a-b78f-33ef544e05c3.png)
![th-643221274](https://user-images.githubusercontent.com/109885044/195506303-316674da-a10a-4176-b0a6-95fe65728062.jpg)

**Comment by soundsnow** [comment]
![Screenshot_20221013-222009_Trebuchet](https://user-images.githubusercontent.com/109885044/195622838-3f037d76-9b7d-4875-9534-acf5c6e44ddf.png)
![Screenshot_20221013-222020_Trebuchet](https://user-images.githubusercontent.com/109885044/195622851-46329f53-fe28-44b5-ade8-130679c875c6.png)
![Screenshot_20221013-222028_Trebuchet](https://user-images.githubusercontent.com/109885044/195622857-39ebc0e1-3afb-48f5-8d76-2d7efc91cebf.png)

**Comment by williehwc** [comment]
This is not a feature I am interested in implementing.
