### ISSUE TITLE
warp to show long file names

### ISSUE THREAD

**Issue by soundsnow** [williehwc/wonderdroid-x#60]
SNK vs. Capcom - Gekitotsu Card Fighters - SNK Supporter Version (Japan) (Beta).ngc
King of Fighters R-1 - Pocket Kakutou Series & Melon-chan no Seichou Nikki (Japan) (Demo).ngp
NBA Action Starring David Robinson (USA, Brazil) (En) (Beta) (1994-03-04) (Alt).gg

**Comment by williehwc** [comment]
There are other issues on long file names. Please do not post duplicate issues.
