### ISSUE TITLE
remove string "empty" and "slot "

### ISSUE THREAD

**Issue by soundsnow** [williehwc/wonderdroid-x#63]
Empty slots do not show the date, the slot that shows the date must have been saved

remove duplicates
    <string name="empty">Empty</string>
    <string name="empty">無し</string>
    <string name="empty">空</string>
    <string name="empty">空</string>

![Screenshot_20221013-192634_Trebuchet](https://user-images.githubusercontent.com/109885044/195602740-40c8c6c0-c176-4acd-bfb8-a3204de12f58.png)

**Comment by williehwc** [comment]
Closing because this is a preferential issue that I don't agree with.
