### ISSUE TITLE
AMOLED Pure Black

### ISSUE THREAD

**Issue by soundsnow** [williehwc/wonderdroid-x#66]
hey, it's not pure black
![Screenshot_20221013-221227_Trebuchet](https://user-images.githubusercontent.com/109885044/195621933-b69696ab-d1be-4f3f-aba9-4ae0eb8c2a50.png)
![Screenshot_20221013-221036_Trebuchet](https://user-images.githubusercontent.com/109885044/195621992-4d49368f-1b67-4f7b-b76d-df1b06216b87.png)
![Screenshot_20221013-221210_Trebuchet](https://user-images.githubusercontent.com/109885044/195622005-14a3c514-fa74-4ecd-b592-a4c6a8505ead.png)
![Screenshot_20221013-221136_Trebuchet](https://user-images.githubusercontent.com/109885044/195622009-bc17d60c-f49f-4a17-8243-b0b365acb7f9.png)

**Comment by soundsnow** [comment]
R 48
G 48
B 48
Alpha 100%
#FF303030

R 0
G 0
B 0
Alpha 100%
#FF000000
![image117](https://user-images.githubusercontent.com/109885044/195622116-8ea2a5db-3bbc-46f7-b87a-9aa639a40372.png)

**Comment by williehwc** [comment]
This is a design decision.
- Most users don't spend a lot of time in the Preferences, so it should not have much effect on battery life.
- Dark gray backgrounds help reduce the effects of screen reflection, which improves the appearance of menus.
