### ISSUE TITLE
pc2 file format, Fire Lancer, Pure Black Background

### ISSUE THREAD

**Issue by AngelofMe** [williehwc/wonderdroid-x#7]
Extensions¶

    .ws
    .wsc
    .pc2 (Benesse Pocket Challenge v2 files)

To run Pocket Challenge V2 software, .ws ⇔ .pc2. 

Games
Fire Lancer (USA) (Demo) (2018-12-25) (Aftermarket) (Unl).wsc
Fire Lancer (USA) (Demo) (2019-01-03) (Aftermarket) (Unl).wsc
You're using an incompatible emulator
![Screenshot_20220606-091531_Trebuchet](https://user-images.githubusercontent.com/26894447/172079425-78a30d52-e057-46fe-87b5-be6842d38900.png)

Dark mode - pure black for AMOLED screen and eyes

Fast-forward button

Recent Content/Played/Games

search bar

WonderWitch homebrew games
WonderWitch (Japan) (FreyaOS 1.0.0) (Program)
WonderWitch (Japan) (FreyaOS 1.0.2) (Program)
WonderWitch (Japan) (FreyaOS 1.0.3) (Program)
WonderWitch (Japan) (FreyaOS 1.1.1) (Program)
WonderWitch (Japan) (FreyaOS 1.1.2) (Program)
WonderWitch (Japan) (FreyaOS 1.1.3) (Program)
WonderWitch (Japan) (FreyaOS 1.1.4) (Program)
WonderWitch (Japan) (FreyaOS 1.1.5) (Program)
WonderWitch (Japan) (FreyaOS 1.1.6b1) (Program)
WonderWitch (Japan) (FreyaOS 1.2.0) (Program)

**Comment by williehwc** [comment]
Thank you for your feedback! This emulator will be moving to Mednafen's code base later this year, which should work with a wider variety of games compared to the current version. I will include Fire Lancer as part of my testing and leave this issue open until it is done.

**Comment by williehwc** [comment]
Good news, Fire Lancer will work in the next version of this emulator. Thanks for letting me know about this game!
I will also make the game selection screen's background pure black in the next version, as long as the "Show game select background" option is turned off in the Preferences.
If you wish to play Benesse Pocket Challenge V2 games, you can rename the pc2 extension to ws or wsc. I don't plan to add recognition of the pc2 extension.
Other feature requests may be considered, but no guarantees.
I will leave this issue open until the next version of this emulator is released.
